version: '3.8'

networks:
  easy-bites-network:
    driver: bridge

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: easy-bites-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: easy-bites
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - easy-bites-network

  # API Gateway Service
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: easy-bites-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/easy-bites
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET_KEY=Y2hhbGxlbmdlZG9lMDAwMTIzNDU2Nzg5YWJjZGVmZ2hpamtsbW5vcHFycw==
      - JWT_EXPIRATION=3600000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - easy-bites-network

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: easy-bites-auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/easy-bites
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET_KEY=Y2hhbGxlbmdlZG9lMDAwMTIzNDU2Nzg5YWJjZGVmZ2hpamtsbW5vcHFycw==
      - JWT_EXPIRATION=3600000
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=adminpass
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - easy-bites-network

  # Restaurant Service
  restaurant-service:
    build:
      context: ./restaurant-service
      dockerfile: Dockerfile
    container_name: easy-bites-restaurant-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/easy-bites
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - easy-bites-network

  # Order Service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: easy-bites-order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/easy-bites
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - easy-bites-network

  # Delivery Service
  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    container_name: easy-bites-delivery-service
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/easy-bites
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - easy-bites-network

volumes:
  mysql-data:
