package com.ds.commons.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ExceptionCode {
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_NOT_AUTHORIZED("USER_NOT_AUTHORIZED"),
    USER_NOT_AUTHENTICATED("USER_NOT_AUTHENTICATED"),
    USER_NOT_VALID("USER_NOT_VALID"),
    INVALID_DATE_FORMAT("INVALID_DATE_FORMAT"),
    ROLE_NOT_FOUND("ROLE_NOT_FOUND"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    INVALID_BUDGET("INVALID_BUDGET"),
    INVALID_USER_TYPE("INVALID_USER_TYPE"),
    MENU_CATEGORY_NOT_FOUND("MENU_CATEGORY_NOT_FOUND"),
    MENU_CATEGORY_ALREADY_EXISTS("MENU_CATEGORY_ALREADY_EXISTS_FOR_RESTAURANT"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    FOOD_ITEM_ALREADY_EXISTS("FOOD_ITEM_ALREADY_EXISTS"),
    RESTAURANT_NOT_FOUND("RESTAURANT_NOT_FOUND"),
    RESTAURANT_ALREADY_EXISTS("RESTAURANT_ALREADY_EXISTS"),
    MISSING_REQUIRED_FIELDS("MISSING_REQUIRED_FIELDS"),
    INVALID_VEHICLE_TYPE("INVALID_VEHICLE_TYPE"),
    LICENSE_ALREADY_EXISTS("LICENSE_ALREADY_EXISTS"),
    VEHICLE_NUMBER_ALREADY_EXISTS("VEHICLE_NUMBER_ALREADY_EXISTS"),
    DRIVER_NOT_FOUND("Driver not found"),
    ORDER_NOT_FOUND("Invalid order. Not available"),
    DRIVER_NOT_AVAILABLE("Complete the current order first"),
    DRIVER_ACCEPTED_ORDER("Order is already in progress."),
    CUSTOMER_NOT_FOUND("Customer not found"),
    DELIVERY_NOT_FOUND("Delivery not found"),
    NO_DELIVERY_HISTORY("No completed delivery found"),
    NO_ACTIVE_HISTORY("No active delivery found"),
    EMAIL_UNAVAILABLE("Email feature is currently unavailable."),
    GEOCODING_UNAVAILABLE("Geocoding is currently unavailable"),
    EMAIL_SEND_FAILURE("Failed to send email"),;

    private final String exceptionCode;
}
