package com.ds.commons.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ExceptionCode {
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_NOT_AUTHORIZED("USER_NOT_AUTHORIZED"),
    USER_NOT_AUTHENTICATED("USER_NOT_AUTHENTICATED"),
    USER_NOT_VALID("USER_NOT_VALID"),
    INVALID_DATE_FORMAT("INVALID_DATE_FORMAT"),
    ROLE_NOT_FOUND("ROLE_NOT_FOUND"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    INVALID_BUDGET("INVALID_BUDGET"),
    INVALID_USER_TYPE("INVALID_USER_TYPE"),

    MENU_CATEGORY_NOT_FOUND("MENU_CATEGORY_NOT_FOUND"),
    MENU_CATEGORY_ALREADY_EXISTS("MENU_CATEGORY_ALREADY_EXISTS_FOR_RESTAURANT"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    FOOD_ITEM_ALREADY_EXISTS("FOOD_ITEM_ALREADY_EXISTS"),
    RESTAURANT_NOT_FOUND("RESTAURANT_NOT_FOUND"),
    RESTAURANT_ALREADY_EXISTS("RESTAURANT_ALREADY_EXISTS"),
    MISSING_REQUIRED_FIELDS("MISSING_REQUIRED_FIELDS"),

    //orderService
    CART_NOT_FOUND("CART_NOT_FOUND"),
    ITEM_NOT_FOUND_IN_CART("ITEM_NOT_FOUND_IN_CART"),
    CANNOT_MODIFY_NON_ACTIVE_CART("CANNOT_MODIFY_NON_ACTIVE_CART"),
    CANNOT_CHECKOUT_NON_ACTIVE_CART("CANNOT_CHECKOUT_NON_ACTIVE_CART"),
    ORDER_NOT_FOUND("ORDER_NOT_FOUND"),
    CANNOT_CREATE_ORDER_FROM_CART("CANNOT_CREATE_ORDER_FROM_CART"),
    CANNOT_CANCEL_NON_PENDING_ORDER("CANNOT_CANCEL_NON_PENDING_ORDER"),
    INVALID_ORDER_STATUS("INVALID_ORDER_STATUS");

    private final String exceptionCode;
}
