package com.ds.commons.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ExceptionCode {
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
    USER_NOT_AUTHORIZED("USER_NOT_AUTHORIZED"),
    USER_NOT_AUTHENTICATED("USER_NOT_AUTHENTICATED"),
    USER_NOT_VALID("USER_NOT_VALID"),
    INVALID_DATE_FORMAT("INVALID_DATE_FORMAT"),
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND"),
    CATEGORY_ALREADY_EXISTS("CATEGORY_ALREADY_EXISTS"),
    DUPLICATE_CATEGORY_ID("DUPLICATE_CATEGORY_ID"),
    DUPLICATE_CATEGORY_NAME("DUPLICATE_CATEGORY_NAME"),
    INCOME_NOT_FOUND("INCOME_NOT_FOUND"),
    EXPENSE_NOT_FOUND("EXPENSE_NOT_FOUND"),
    INVALID_AMOUNT("INVALID_AMOUNT"),
    INVALID_CATEGORY("INVALID_CATEGORY"),
    BUDGET_NOT_FOUND("BUDGET_NOT_FOUND"),
    INVALID_BUDGET("INVALID_BUDGET"),
    OVERLAPPING_BUDGET("OVERLAPPING_BUDGET");

    private final String exceptionCode;
}
