export enum USER_TYPES {
    ROLE_CUSTOMER = "ROLE_CUSTOMER",
    ROLE_RESTAURANT_MANAGER = "ROLE_RESTAURANT_MANAGER",
    ROLE_DELIVERY_PERSON = "ROLE_DELIVERY_PERSON",
    ROLE_SYSTEM_ADMIN = "ROLE_SYSTEM_ADMIN",
}