server:
  port: 8080

security:
  jwt:
    secret-key: "Y2hhbGxlbmdlZG9lMDAwMTIzNDU2Nzg5YWJjZGVmZ2hpamtsbW5vcHFycw=="

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081  # Direct URL to auth service
          predicates:
            - Path=/auth/**
          filters:
            - ValidateJWT  # Optional if you want JWT validation here

        - id: master-service
          uri: http://localhost:8082  # Direct URL to master service
          predicates:
            - Path=/api/**
          filters:
            - name: ValidateJWT
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin



